import type { AssetRecord } from "./types";

export const ASSETS: AssetRecord[] = [
  {
    id: "7a4d19d1-1a4d-4d14-9ce5-4fdab1000001",
    assetCode: "AST-VEH-001",
    assetName: "Forklift Alpha-01",
    assetType: "vehicle",
    category: "material_handling",
    vehicleType: "forklift",
    make: "Toyota",
    model: "8FBE20",
    manufactureYear: 2021,
    registrationNumber: "WP PF-4581",
    vin: "VIN-ALPHA-0001",
    status: "active",
    healthBand: "good",
    criticalityScore: 82,
    warehouse: {
      id: "wh-001",
      code: "WH-A",
      name: "Warehouse A",
    },
    assignedTo: {
      id: "usr-001",
      name: "Sahan Silva",
      email: "sahan@predictix.lk",
    },
    currentMileage: 18420,
    purchaseDate: "2022-03-14",
    warrantyExpiryDate: "2027-03-14",
    lastServiceDate: "2026-02-01",
    nextServiceDate: "2026-04-10",
    description:
      "Primary electric forklift used for pallet transport and stacking in receiving and aisle sections.",
    vehicleRole: "material_handling",
    makeModel: "Toyota 8FBE20",
    fuelType: "electric",
    transmission: "automatic",
    serviceProviderType: "authorized_vendor",
    payloadCapacityKg: 2000,
    maintenancePriority: "medium",
    vehicleAgeYears: 4,
    lifetimeServiceCount: 6,
    lifetimeBreakdownCount: 1,
    prediction: {
      healthScore: 86,
      failureProbability: 0.18,
      confidence: 0.89,
      predictedMaintenanceDate: "2026-04-06",
      daysUntilMaintenance: 9,
      estimatedCost: 22000,
      minCost: 18000,
      maxCost: 28000,
      currency: "LKR",
      topExplanations: [
        "Battery health trend has declined over the last 30 days.",
        "Start-stop burden increased during peak usage hours.",
        "Mileage since last service is above the recent fleet average.",
      ],
    },
    maintenanceEvents: [
      {
        id: "me-001",
        eventType: "preventive",
        title: "Battery and brake inspection",
        scheduledDate: "2026-02-01T09:00:00Z",
        performedAt: "2026-02-01T11:30:00Z",
        performedBy: { id: "usr-010", name: "Dinithi Jay" },
        odometerReading: 17600,
        downtimeHours: 2.5,
        costAmount: 14500,
        currency: "LKR",
        vendorName: "Lanka Lift Services",
        notes: "Battery connectors cleaned. Brake wear within expected range.",
      },
    ],
    assignmentHistory: [
      {
        id: "as-001",
        user: { id: "usr-001", name: "Sahan Silva" },
        assignedBy: { id: "adm-001", name: "Admin User" },
        assignedAt: "2026-01-15T08:00:00Z",
        isActive: true,
        notes: "Assigned for regular warehouse operations.",
      },
    ],
    auditTrail: [
      {
        id: "au-001",
        field: "status",
        oldValue: "inactive",
        newValue: "active",
        changedBy: { id: "adm-001", name: "Admin User" },
        createdAt: "2026-01-15T08:00:00Z",
        reason: "Returned to service after inspection",
      },
    ],
  },
  {
    id: "7a4d19d1-1a4d-4d14-9ce5-4fdab1000002",
    assetCode: "AST-VEH-002",
    assetName: "Conveyor Belt B-12",
    assetType: "vehicle",
    category: "automation",
    vehicleType: "conveyor_support_unit",
    make: "Siemens",
    model: "CB-12X",
    manufactureYear: 2020,
    registrationNumber: null,
    vin: "VIN-CONV-0012",
    status: "under_maintenance",
    healthBand: "moderate",
    criticalityScore: 74,
    warehouse: {
      id: "wh-001",
      code: "WH-A",
      name: "Warehouse A",
    },
    assignedTo: null,
    currentMileage: 0,
    purchaseDate: "2021-01-20",
    warrantyExpiryDate: null,
    lastServiceDate: "2026-01-29",
    nextServiceDate: "2026-03-30",
    description:
      "Outbound conveyor support unit with recent vibration irregularities and belt misalignment reports.",
    vehicleRole: "sorting_support",
    makeModel: "Siemens CB-12X",
    fuelType: "electric",
    transmission: null,
    serviceProviderType: "internal",
    payloadCapacityKg: null,
    maintenancePriority: "high",
    vehicleAgeYears: 5,
    lifetimeServiceCount: 11,
    lifetimeBreakdownCount: 2,
    prediction: {
      healthScore: 68,
      failureProbability: 0.47,
      confidence: 0.81,
      predictedMaintenanceDate: "2026-03-31",
      daysUntilMaintenance: 3,
      estimatedCost: 48000,
      minCost: 39000,
      maxCost: 60000,
      currency: "LKR",
      topExplanations: [
        "Vibration RMS increased beyond normal operating band.",
        "Downtime hours in the past 90 days are elevated.",
        "Recent inspection notes indicate recurring belt tension issues.",
      ],
    },
    maintenanceEvents: [
      {
        id: "me-002",
        eventType: "repair",
        title: "Belt alignment correction",
        scheduledDate: "2026-03-27T08:30:00Z",
        performedAt: null,
        performedBy: null,
        downtimeHours: 6,
        costAmount: 32000,
        currency: "LKR",
        vendorName: "Internal Maintenance Team",
        notes: "Waiting for replacement roller delivery.",
      },
      {
        id: "me-003",
        eventType: "inspection",
        title: "Emergency vibration inspection",
        performedAt: "2026-03-20T10:15:00Z",
        performedBy: { id: "usr-011", name: "Kavindu Perera" },
        costAmount: 6000,
        currency: "LKR",
        notes: "Abnormal vibration detected near drive section.",
      },
    ],
    assignmentHistory: [],
    auditTrail: [
      {
        id: "au-002",
        field: "status",
        oldValue: "active",
        newValue: "under_maintenance",
        changedBy: { id: "adm-001", name: "Admin User" },
        createdAt: "2026-03-27T08:10:00Z",
        reason: "Sent for repair after inspection finding",
      },
    ],
  },
  {
    id: "7a4d19d1-1a4d-4d14-9ce5-4fdab1000003",
    assetCode: "AST-VEH-003",
    assetName: "Loading Dock Crane LD-03",
    assetType: "vehicle",
    category: "heavy_equipment",
    vehicleType: "loading_crane",
    make: "Komatsu",
    model: "LD-03",
    manufactureYear: 2018,
    registrationNumber: "WP CR-9032",
    vin: "VIN-LD03-9032",
    status: "critical",
    healthBand: "critical",
    criticalityScore: 95,
    warehouse: {
      id: "wh-002",
      code: "WH-B",
      name: "Warehouse B",
    },
    assignedTo: { id: "usr-013", name: "Nimal Perera" },
    currentMileage: 54210,
    purchaseDate: "2019-06-12",
    warrantyExpiryDate: null,
    lastServiceDate: "2026-01-05",
    nextServiceDate: "2026-03-29",
    description:
      "Critical dock crane with hydraulic pressure instability and recurring motor temperature spikes.",
    vehicleRole: "loading_operations",
    makeModel: "Komatsu LD-03",
    fuelType: "diesel",
    transmission: "automatic",
    serviceProviderType: "authorized_vendor",
    payloadCapacityKg: 4500,
    maintenancePriority: "urgent",
    vehicleAgeYears: 7,
    lifetimeServiceCount: 18,
    lifetimeBreakdownCount: 5,
    prediction: {
      healthScore: 42,
      failureProbability: 0.87,
      confidence: 0.94,
      predictedMaintenanceDate: "2026-03-29",
      daysUntilMaintenance: 1,
      estimatedCost: 125000,
      minCost: 98000,
      maxCost: 155000,
      currency: "LKR",
      topExplanations: [
        "Hydraulic health is sharply reduced.",
        "Active fault code count increased in recent readings.",
        "Engine temperature and downtime trend both worsened.",
      ],
    },
    maintenanceEvents: [
      {
        id: "me-004",
        eventType: "breakdown",
        title: "Hydraulic pressure drop incident",
        performedAt: "2026-03-25T13:45:00Z",
        performedBy: { id: "usr-014", name: "Malsha Fernando" },
        downtimeHours: 8,
        costAmount: 18000,
        currency: "LKR",
        vendorName: "Internal Team",
        notes: "Temporary shutdown initiated for safety.",
      },
      {
        id: "me-005",
        eventType: "scheduled_service",
        title: "Hydraulic system service",
        scheduledDate: "2026-03-29T09:00:00Z",
        performedAt: null,
        performedBy: null,
        costAmount: 95000,
        currency: "LKR",
        vendorName: "HeavyMach Services",
        notes: "Awaiting approval and spare parts.",
      },
    ],
    assignmentHistory: [
      {
        id: "as-002",
        user: { id: "usr-013", name: "Nimal Perera" },
        assignedBy: { id: "adm-001", name: "Admin User" },
        assignedAt: "2025-11-01T09:00:00Z",
        isActive: true,
      },
    ],
    auditTrail: [
      {
        id: "au-003",
        field: "health_band",
        oldValue: "poor",
        newValue: "critical",
        changedBy: { id: "adm-001", name: "Admin User" },
        createdAt: "2026-03-25T14:00:00Z",
        reason: "Failure prediction crossed critical threshold",
      },
    ],
  },
  {
    id: "7a4d19d1-1a4d-4d14-9ce5-4fdab1000004",
    assetCode: "AST-VEH-004",
    assetName: "Delivery Van DV-07",
    assetType: "vehicle",
    category: "transport",
    vehicleType: "van",
    make: "Toyota",
    model: "HiAce",
    manufactureYear: 2022,
    registrationNumber: "CAB-7821",
    vin: "VIN-DV07-7821",
    status: "inactive",
    healthBand: "good",
    criticalityScore: 55,
    warehouse: {
      id: "wh-003",
      code: "WH-C",
      name: "Warehouse C",
    },
    assignedTo: null,
    currentMileage: 26750,
    purchaseDate: "2022-08-03",
    warrantyExpiryDate: "2027-08-03",
    lastServiceDate: "2026-02-14",
    nextServiceDate: "2026-05-10",
    description: "Regional transport van currently parked and temporarily inactive.",
    vehicleRole: "delivery",
    makeModel: "Toyota HiAce",
    fuelType: "diesel",
    transmission: "manual",
    serviceProviderType: "authorized_vendor",
    payloadCapacityKg: 1200,
    maintenancePriority: "low",
    vehicleAgeYears: 3,
    lifetimeServiceCount: 5,
    lifetimeBreakdownCount: 0,
    prediction: {
      healthScore: 81,
      failureProbability: 0.12,
      confidence: 0.77,
      predictedMaintenanceDate: "2026-05-08",
      daysUntilMaintenance: 41,
      estimatedCost: 16000,
      minCost: 12000,
      maxCost: 22000,
      currency: "LKR",
      topExplanations: [
        "Vehicle age and mileage remain within expected range.",
        "Recent service completed successfully.",
      ],
    },
    maintenanceEvents: [],
    assignmentHistory: [],
    auditTrail: [
      {
        id: "au-004",
        field: "status",
        oldValue: "active",
        newValue: "inactive",
        changedBy: { id: "adm-001", name: "Admin User" },
        createdAt: "2026-03-15T09:30:00Z",
        reason: "Temporarily not in deployment plan",
      },
    ],
  },
  {
    id: "7a4d19d1-1a4d-4d14-9ce5-4fdab1000005",
    assetCode: "AST-VEH-005",
    assetName: "Pallet Mover PM-02",
    assetType: "vehicle",
    category: "material_handling",
    vehicleType: "pallet_mover",
    make: "Jungheinrich",
    model: "EJE 120",
    manufactureYear: 2017,
    registrationNumber: null,
    vin: "VIN-PM02-2017",
    status: "decommissioned",
    healthBand: "poor",
    criticalityScore: 21,
    warehouse: {
      id: "wh-001",
      code: "WH-A",
      name: "Warehouse A",
    },
    assignedTo: null,
    currentMileage: null,
    purchaseDate: "2018-02-18",
    warrantyExpiryDate: null,
    lastServiceDate: "2025-10-18",
    nextServiceDate: null,
    description: "Old pallet mover retired from active use after repeated faults.",
    vehicleRole: "material_handling",
    makeModel: "Jungheinrich EJE 120",
    fuelType: "electric",
    transmission: null,
    serviceProviderType: "internal",
    payloadCapacityKg: 1200,
    maintenancePriority: "none",
    vehicleAgeYears: 9,
    lifetimeServiceCount: 16,
    lifetimeBreakdownCount: 7,
    prediction: {
      healthScore: 28,
      failureProbability: 0.73,
      confidence: 0.7,
      predictedMaintenanceDate: null,
      daysUntilMaintenance: null,
      estimatedCost: 0,
      minCost: 0,
      maxCost: 0,
      currency: "LKR",
      topExplanations: ["Asset has been retired from service."],
    },
    maintenanceEvents: [
      {
        id: "me-006",
        eventType: "replacement",
        title: "Replaced by new pallet mover",
        performedAt: "2026-02-05T10:00:00Z",
        performedBy: { id: "adm-001", name: "Admin User" },
        notes: "Removed from active inventory.",
      },
    ],
    assignmentHistory: [],
    auditTrail: [
      {
        id: "au-005",
        field: "status",
        oldValue: "under_maintenance",
        newValue: "decommissioned",
        changedBy: { id: "adm-001", name: "Admin User" },
        createdAt: "2026-02-05T10:00:00Z",
        reason: "Asset replacement approved",
      },
    ],
  },
];